name: ottaa_project_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.1.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^6.0.0
  either_dart: ^0.2.0
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  flutter_facebook_auth: ^4.4.1+1
  flutter_riverpod: ^2.0.2
  flutter_tts: ^3.5.3
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_theme: ^4.0.1+4
  just_audio: ^0.9.29
  package_info_plus: ^2.0.0
  picto_widget: 0.0.3
  screenshot: ^1.2.3
  share_plus: ^5.0.0
  url_launcher: ^6.1.6
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  syncfusion_flutter_charts: ^20.3.56
  textfield_datepicker: ^0.1.0
  sqflite: ^2.2.0+3
  path: ^1.8.2
  cached_network_image: ^3.2.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/
    - assets/profiles/
    - assets/games_images/
    - assets/audios/
    - assets/languages/
    - assets/gender_based/
    - assets/gender_based/pictos/
    - assets/gender_based/grupos/
    - assets/i18n/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
    - family: OTTAAProjectCustomIcon
      fonts:
        - asset: assets/custom_icons/Ottaa_project_custom_icons.ttf
