name: ottaa_project_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  either_dart: ^0.3.0
  firebase_analytics: ^10.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.5
  firebase_database: ^10.0.5
  firebase_storage: ^11.0.5
  flutter_facebook_auth: ^5.0.6
  flutter_riverpod: ^2.0.2
  flutter_tts: ^3.5.3
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_theme: ^4.0.1+4
  just_audio: ^0.9.29
  package_info_plus: ^3.0.2
  picto_widget: ^0.0.5+5
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  url_launcher: ^6.1.6
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  syncfusion_flutter_charts: ^20.3.56
  textfield_datepicker: ^0.1.0
  sqflite: ^2.2.0+3
  path: ^1.8.2
  cached_network_image: ^3.2.2
  transparent_image: ^2.0.0
  ottaa_ui_kit:
    git:
      url: https://github.com/OTTAA-Project/OTTAA_flutter_theme.git
      ref: master
  rive: ^0.9.1
  collection: ^1.16.0
  firebase_messaging: ^14.2.1
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mockito: ^5.3.2
  test: ^1.22.0

dependency_overrides:
  #  firebase_core_platform_interface: 4.5.1
  test_api: 0.4.12


flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/
    - assets/edit/
    - assets/edit/picto/
    - assets/board/
    - assets/board/icons/
    - assets/board/icons/icons_not_selected/
    - assets/board/icons/icons_selected/
    - assets/profiles/
    - assets/games_images/
    - assets/audios/
    - assets/languages/
    - assets/gender_based/
    - assets/gender_based/pictos/
    - assets/gender_based/grupos/
    - assets/i18n/
    - assets/profile/
    - assets/rive/
    - assets/onboarding/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
    - family: OTTAAProjectCustomIcon
      fonts:
        - asset: assets/custom_icons/Ottaa_project_custom_icons.ttf
