name: ottaa_project_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter_facebook_auth: ^3.5.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_tts: ^3.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  get_it: ^7.2.0
  go_router: ^5.0.5
  flutter_riverpod: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_theme: ^4.0.1+4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/