name: ottaa_project_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.1.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^6.0.0
  either_dart: ^0.2.0
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  flutter_facebook_auth: ^4.4.1+1
  flutter_riverpod: ^2.0.2
  flutter_tts: ^3.5.3
  fluttertoast: ^8.1.1
  get_it: ^7.2.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_theme: ^4.0.1+4
  just_audio: ^0.9.29
  package_info_plus: ^2.0.0
  picto_widget: ^0.0.4
  screenshot: ^1.2.3
  share_plus: ^5.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/
